### PR TITLE
Reject invalid inputs in price utilities

### LINKED ISSUE #5904: Price utilities fail to reject invalid inputs in price/main.go, xdr/prices.go
In `price/main.go`:
- MulFractionRoundDown() and mulFractionRoundUp() unsafely cast arguments of type `int64` to `uint64`
In `xdr/prices.go`:
- Price.Cheaper() casts its `Int32` components to `uint64` prior to comparison, which could provide an inverse result if negative components exist.
- String() and Normalize() both fail to check that the denominator isn't 0, which would cause an unhandled panic in big.Rat.

### Root causes
```
// price/main.go::MulFractionRoundDown/Up()
func ...(x int64, n int64, d int64) (int64, error) {
	if d == 0 {
		return 0, ErrDivisionByZero
	}
        // BUG: meaningless result if x < 0 or n < 0
	hi, lo := bits.Mul64(uint64(x), uint64(n))
        ...
}
```
```
// xdr/prices.go::Price.Cheaper
func (p Price) Cheaper(q Price) bool {
        // BUG: meaningless result if p.N, p.D, q.N, q.D < 0 (these are Int32 fields)
	return uint64(p.N)*uint64(q.D) < uint64(q.N)*uint64(p.D)
}
...
// xdr/prices.go::Price.String
func (p Price) String() string {
        # BUG: unhandled panic in big.NewRat if p.D == 0
	return big.NewRat(int64(p.N), int64(p.D)).FloatString(7)
}
...
// xdr/prices.go::Price.Normalize
func (p *Price) Normalize() {
         # BUG: unhandled panic in big.NewRat if p.D == 0
	r := big.NewRat(int64(p.N), int64(p.D))
	p.N = Int32(r.Num().Int64())
	p.D = Int32(r.Denom().Int64())
}
```

### Impact
- MulFractionRoundDown() and mulFractionRoundUp(), and Price.Cheaper() will produce an unintended/meaningless uint64 result if one of their Int32 fields are less than 0.
- Price.String and Price.Normalize panic instead of failing gracefully if p.D == 0.

### PR DESCRIPTION
**Pull request by cjonas9**
### What
In `xdr/prices.go::Price.Cheaper()`, `prices/main.go::MulFractionRoundDown()` and `prices/main.go::mulFractionRoundUp()`, `Int32` and `Int64` values are cast to `uint64` values, which would wrap to large, meaningless values. Then, there are several `big.Rat()` calls where the denominator is checked to not be zero, which would cause an unrecoverable panic. 

For `xdr/prices.go`, because fixing these would cause breaking changes, this adds equivalent `Try*()` methods that implement their corresponding methods with errors returned instead of panicking/returning invalid output. The new methods are unit tested as the old ones are, along with a new test to ensure invalid output is rejected.

The old methods are marked as deprecated, except for Price.String() as this implements the Stringer interface -- this case is still also changed to be handled without panic.

### Why

This adds defensive programming methods for developers utilizing these functions, but note that functions are already called safely in Stellar services.

### Known limitations

N/A

### CODE REVIEW

**Comment by tamirms** [comment]
Below are specific comments with actionable suggestions and evidence from the Go standard library.

---

### 1. Remove `fmt.Printf` (Libraries should not print to stdout)

**The Issue:**
In `xdr/price.go`, the `String()` method prints to stdout:

```go
fmt.Printf("cannot stringify invalid price: %v\n", err)

```

**Why this matters:**
Libraries should never write directly to standard output. It spams the logs of consuming applications, interferes with CLI tools that rely on stdout for data piping, and bypasses the application's structured logging system.

**Standard Library Evidence:**
Look at **`net/http`**. When the HTTP server encounters an error, it doesn't print to stdout; it uses a configurable `*log.Logger` (see `Server.ErrorLog`). If that isn't set, it degrades gracefully or returns the error to the caller. It never assumes it owns `os.Stdout`.

**Actionable Suggestion:**
Remove the `fmt.Printf` call entirely. The `String()` method should simply return the descriptive string. If the application cares about the invalid state, they can log it themselves using the returned value.

---

### 2. Make `String()` Safe, Not Silent

**The Issue:**
Currently, `String()` returns `"INVALID"` when validation fails. This hides the actual data causing the problem, making debugging harder for the user.

**Standard Library Evidence:**
Look at **`net.IP.String()`**. If an IP address is nil or empty, it doesn't panic, nor does it return a generic `"INVALID"` string. It returns `"<nil>"`.
Similarly, **`reflect.Value.String()`** returns `<invalid Value>` for zero values. The convention is to use angle brackets `<>` to denote a meta-status that isn't a valid value.

**Actionable Suggestion:**
Return a string that describes the invalid state including the raw values. This satisfies `fmt.Stringer` without masking the data.

```go
func (p Price) String() string {
    if err := p.Validate(); err != nil {
        // Returns something like "<invalid price (10/0): denominator cannot be zero>"
        return fmt.Sprintf("<invalid price (%d/%d): %v>", p.N, p.D, err)
    }
    // ... existing logic
}

```

---

### 3. Avoid Silent Failures in Boolean Methods (`Cheaper`, `Equal`)

**The Issue:**
The PR modifies `Cheaper` and `Equal` to return `false` (and print to stdout) if the price is invalid.

```go
if err := p.Validate(); err != nil {
    fmt.Printf(...)
    return false
}

```

**Why this is risky:**
This creates a **silent failure**. In a financial context, if `Price A` is invalid, reporting that it is *not* cheaper than `Price B` (returning `false`) implies that `Price B` is cheaper or equal. This is mathematically false (the comparison is undefined) and could trick a trading algorithm into executing a bad trade.

**Standard Library Evidence:**
When the **`encoding/json`** package encounters a situation where it cannot guarantee correctness (like a syntax error), it doesn't try to "guess" or return a default zero-value; it returns a `SyntaxError`.
While we cannot change the signature of `Cheaper` to return an error without breaking the API (v1 compatibility), we should arguably **keep the panic** or explicitly document undefined behavior rather than returning a misleading boolean.

**Actionable Suggestion:**
Since breaking the API is likely not an option, the safest "Band-Aid" is:

1. **Deprecate the unsafe methods:** Mark `Cheaper` and `Equal` as deprecated.
2. **Add Safe Alternatives:** Introduce `SafeCheaper(p Price) (bool, error)`.
3. **Fail loudly in the legacy method:** If you must keep `Cheaper` without errors, do not print to stdout. Just return `false` but ensure the deprecation notice warns users that invalid prices yield undefined results.

---

### 4. Endorsing the `ErrNoNegatives` Pattern

**The Good:**
The changes in `price/main.go` (e.g., `MulFractionRoundDown`) where you added checks for `ErrNoNegatives` are **perfect**.

**Standard Library Evidence:**
This mirrors **`strconv.Atoi`**. It doesn't panic on bad input; it returns `0` and a `*NumError`. By returning `ErrNoNegatives`, you are adhering to the "Errors are Values" philosophy of Go.

**Actionable Suggestion:**
This part of the PR is solid. Just ensure there is a unit test case specifically for this negative input to ensure the error is returned as expected.

File: xdr/price.go [hunk 1]
```diff
@@ -1,26 +1,57 @@
 package xdr
 
 import (
+	"fmt"
 	"math/big"
+
+	"github.com/stellar/go-stellar-sdk/support/errors"
```
Comment (karthikiyer56) [inline xdr/price.go]: Yes, we have this packge from old times, but the preference, for a while now, has been to use the updated error formatting support in `fmt`, especially with `%w` for error wrapping

so, something like 

`fmt.Errorf("failed to fetch data for ID %d: %w", id, err)`

File: xdr/price.go [hunk 2]
```diff
@@ -1,26 +1,57 @@
...
+	if err := p.Validate(); err != nil {
+		return fmt.Sprintf("<invalid price (%d/%d): %v>", p.N, p.D, err)
+	}
 	return big.NewRat(int64(p.N), int64(p.D)).FloatString(7)
 }
 
-// Equal returns whether the price's value is the same,
+// TryString returns a string representation of `p` if `p` is valid,
+// and an error otherwise.
+func (p Price) TryString() (string, error) {
```
Comment (karthikiyer56) [inline xdr/price.go]: I see that you incorporated Tamir's recommendation about surfacing the appropriate error message with `<...>` in the `Streing()` method. 
We dont need this `TryString()` method at all.
`String` is one method that doesnt need a `Try*` counterpart that returns error as well

File: xdr/price.go [hunk 3]
```diff
@@ -1,26 +1,57 @@
...
+// TryEqual returns whether the price's value is the same,
 // taking into account denormalized representation
 // (e.g. Price{1, 2}.EqualValue(Price{2,4}) == true )
-func (p Price) Equal(q Price) bool {
-	// See the Cheaper() method for the reasoning behind this:
-	return uint64(p.N)*uint64(q.D) == uint64(q.N)*uint64(p.D)
+// Returns an error if either price is invalid.
+func (p Price) TryEqual(q Price) (bool, error) {
+	if err := p.Validate(); err != nil {
+		return false, errors.Wrap(err, "invalid price p")
```
Comment (karthikiyer56) [inline xdr/price.go]: `fmt.Errorf` everywhere pl

File: xdr/price_test.go [hunk 4]
```diff
@@ -43,11 +89,45 @@ func TestPriceCheaper(t *testing.T) {
...
+	p.Normalize()
+	assert.Equal(t, xdr.Price{N: 1, D: 4}, p)
+
+	// not canonical using deprecated Price.Normalize() method
+	p = xdr.Price{N: 500, D: 2000}
 	p.Normalize()
 	assert.Equal(t, xdr.Price{N: 1, D: 4}, p)
 }
+
+func TestNoInvalid(t *testing.T) {
```
Comment (karthikiyer56) [inline xdr/price_test.go]: nit: `TestInvalidPrices`

**Review by karthikiyer56 — APPROVED** [review]
